const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const UserSchema = new Schema({
    bio: {
        type: String,
        required: false,
        unique: false,
        default:''

    },
    name: {
        type:String,
        required:false,
        unique:false,
        default:''
    },
    username: {
        type: String,
        required: true,
        unique: true
    },
    email: {
        type: String,
        required: true,
        unique: true
    },
    password: {
        type: String,
        required: true
    },
    books: {
        type: [new Schema({
            title: String,
            selectedBook: String,
            description: String,
            rating: Number,
            ratingsCount: Number,
            key:String,
            subject:[],
            coverImage:String,
            publish_date:String,
            pages:String,
            author:String,
        })],   
        default: []     
    },
    bookPattern: {
        type: Map,
        of: Number,
        default: {
            "Arts": 0,
            "Architecture": 0,
            "Art Instruction": 0,
            "Art History": 0,
            "Dance": 0,
            "Design": 0,
            "Fashion": 0,
            "Film": 0,
            "Graphic Design": 0,
            "Music": 0,
            "Music Theory": 0,
            "Painting": 0,
            "Photography": 0,
            "Animals": 0,
            "Bears": 0,
            "Cats": 0,
            "Kittens": 0,
            "Dogs": 0,
            "Puppies": 0,
            "Fiction": 0,
            "Fantasy": 0,
            "Historical Fiction": 0,
            "Horror": 0,
            "Humor": 0,
            "Literature": 0,
            "Magic": 0,
            "Mystery and detective stories": 0,
            "Plays": 0,
            "Poetry": 0,
            "Romance": 0,
            "Science Fiction": 0,
            "Short Stories": 0,
            "Thriller": 0,
            "Young Adult": 0,
            "Science & Mathematics": 0,
            "Biology": 0,
            "Chemistry": 0,
            "Mathematics": 0,
            "Physics": 0,
            "Programming": 0,
            "Business & Finance": 0,
            "Management": 0,
            "Entrepreneurship": 0,
            "Business Economics": 0,
            "Business Success": 0,
            "Finance": 0,
            "Children's": 0,
            "Kids Books": 0,
            "Stories in Rhyme": 0,
            "Baby Books": 0,
            "Bedtime Books": 0,
            "Picture Books": 0,
            "History": 0,
            "Ancient Civilization": 0,
            "Archaeology": 0,
            "Anthropology": 0,
            "World War II": 0,
            "Social Life and Customs": 0,
            "Health & Wellness": 0,
            "Cooking": 0,
            "Cookbooks": 0,
            "Mental Health": 0,
            "Exercise": 0,
            "Nutrition": 0,
            "Self-help": 0,
            "Biography": 0,
            "Autobiographies": 0,
            "History": 0,
            "Politics and Government": 0,
            "World War II": 0,
            "Women": 0,
            "Kings and Rulers": 0,
            "Composers": 0,
            "Artists": 0,
            "Social Sciences": 0,
            "Anthropology": 0,
            "Religion": 0,
            "Political Science": 0,
            "Psychology": 0,
            "Places": 0,
            "Brazil": 0,
            "India": 0,
            "Indonesia": 0,
            "United States": 0,
            "Textbooks": 0,
            "History": 0,
            "Mathematics": 0,
            "Geography": 0,
            "Psychology": 0,
            "Algebra": 0,
            "Education": 0,
            "Business & Economics": 0,
            "Science": 0,
            "Chemistry": 0,
            "English Language": 0,
            "Physics": 0,
            "Computer Science": 0,
            "Books by Language": 0,
            "English": 0
        }
    }
    
});

module.exports = mongoose.model('User', UserSchema);
